package io.github.avaxerrr.qsstoolkit.completion

/**
 * Centralized data for QSS properties, widgets, and values.
 * Used by both CompletionContributor (for suggestions) and ValidationAnnotator (for error checking).
 */
object QssData {

    // Enum to define the expected type of value for validation
    enum class PropertyType {
        COLOR,
        MEASUREMENT, // Requires unit (px, pt) or 0
        NUMBER,      // Raw number (opacity) or Boolean (0/1)
        STRING,      // Generic text or specific enums
        URL,         // Strict URL check (url(...))
        BORDER       // Complex (width style color) - effectively "Any"
    }

    // Map properties to their expected value types
    val PROPERTY_TYPES = mapOf(
        "accent-color" to PropertyType.COLOR,
        "alignment" to PropertyType.STRING,
        "alternate-background-color" to PropertyType.COLOR,
        "backward-icon" to PropertyType.BORDER,
        "background" to PropertyType.BORDER, // Complex (color + url + repeat)
        "background-attachment" to PropertyType.STRING,
        "background-clip" to PropertyType.STRING,
        "background-color" to PropertyType.COLOR,
        "background-image" to PropertyType.BORDER, // Relaxed to allow complex backgrounds
        "background-origin" to PropertyType.STRING,
        "background-position" to PropertyType.STRING,
        "background-repeat" to PropertyType.STRING,
        "border" to PropertyType.BORDER,
        "border-bottom" to PropertyType.BORDER,
        "border-bottom-color" to PropertyType.COLOR,
        "border-bottom-left-radius" to PropertyType.MEASUREMENT,
        "border-bottom-right-radius" to PropertyType.MEASUREMENT,
        "border-bottom-style" to PropertyType.STRING,
        "border-bottom-width" to PropertyType.MEASUREMENT,
        "border-color" to PropertyType.COLOR,
        "border-image" to PropertyType.BORDER, // Relaxed to allow url(...) + numbers
        "border-left" to PropertyType.BORDER,
        "border-left-color" to PropertyType.COLOR,
        "border-left-style" to PropertyType.STRING,
        "border-left-width" to PropertyType.MEASUREMENT,
        "border-radius" to PropertyType.MEASUREMENT,
        "border-right" to PropertyType.BORDER,
        "border-right-color" to PropertyType.COLOR,
        "border-right-style" to PropertyType.STRING,
        "border-right-width" to PropertyType.MEASUREMENT,
        "border-style" to PropertyType.STRING,
        "border-top" to PropertyType.BORDER,
        "border-top-color" to PropertyType.COLOR,
        "border-top-left-radius" to PropertyType.MEASUREMENT,
        "border-top-right-radius" to PropertyType.MEASUREMENT,
        "border-top-style" to PropertyType.STRING,
        "border-top-width" to PropertyType.MEASUREMENT,
        "border-width" to PropertyType.MEASUREMENT,
        "bottom" to PropertyType.MEASUREMENT,
        "button-layout" to PropertyType.NUMBER,
        "cd-icon" to PropertyType.BORDER,
        "color" to PropertyType.COLOR,
        "computer-icon" to PropertyType.BORDER,
        "desktop-icon" to PropertyType.BORDER,
        "dialogbuttonbox-buttons-have-icons" to PropertyType.NUMBER,
        "dialog-apply-icon" to PropertyType.BORDER,
        "dialog-cancel-icon" to PropertyType.BORDER,
        "dialog-close-icon" to PropertyType.BORDER,
        "dialog-discard-icon" to PropertyType.BORDER,
        "dialog-help-icon" to PropertyType.BORDER,
        "dialog-no-icon" to PropertyType.BORDER,
        "dialog-ok-icon" to PropertyType.BORDER,
        "dialog-open-icon" to PropertyType.BORDER,
        "dialog-reset-icon" to PropertyType.BORDER,
        "dialog-save-icon" to PropertyType.BORDER,
        "dialog-yes-icon" to PropertyType.BORDER,
        "directory-closed-icon" to PropertyType.BORDER,
        "directory-icon" to PropertyType.BORDER,
        "directory-link-icon" to PropertyType.BORDER,
        "directory-open-icon" to PropertyType.BORDER,
        "dockwidget-close-icon" to PropertyType.BORDER,
        "downarrow-icon" to PropertyType.BORDER,
        "dvd-icon" to PropertyType.BORDER,
        "filedialog-contentsview-icon" to PropertyType.BORDER,
        "filedialog-detailedview-icon" to PropertyType.BORDER,
        "filedialog-end-icon" to PropertyType.BORDER,
        "filedialog-infoview-icon" to PropertyType.BORDER,
        "filedialog-listview-icon" to PropertyType.BORDER,
        "filedialog-new-directory-icon" to PropertyType.BORDER,
        "filedialog-parent-directory-icon" to PropertyType.BORDER,
        "filedialog-start-icon" to PropertyType.BORDER,
        "file-icon" to PropertyType.BORDER,
        "file-link-icon" to PropertyType.BORDER,
        "floppy-icon" to PropertyType.BORDER,
        "font" to PropertyType.STRING,
        "font-family" to PropertyType.STRING,
        "font-size" to PropertyType.MEASUREMENT,
        "font-style" to PropertyType.STRING,
        "font-weight" to PropertyType.STRING,
        "forward-icon" to PropertyType.BORDER,
        "gridline-color" to PropertyType.COLOR,
        "harddisk-icon" to PropertyType.BORDER,
        "height" to PropertyType.MEASUREMENT,
        "home-icon" to PropertyType.BORDER,
        "icon" to PropertyType.BORDER, // Relaxed
        "icon-size" to PropertyType.MEASUREMENT,
        "image" to PropertyType.BORDER, // Relaxed
        "image-position" to PropertyType.STRING,
        "left" to PropertyType.MEASUREMENT,
        "leftarrow-icon" to PropertyType.BORDER,
        "letter-spacing" to PropertyType.MEASUREMENT,
        "lineedit-clear-button-icon" to PropertyType.BORDER,
        "lineedit-password-character" to PropertyType.NUMBER,
        "lineedit-password-mask-delay" to PropertyType.NUMBER,
        "margin" to PropertyType.MEASUREMENT,
        "margin-bottom" to PropertyType.MEASUREMENT,
        "margin-left" to PropertyType.MEASUREMENT,
        "margin-right" to PropertyType.MEASUREMENT,
        "margin-top" to PropertyType.MEASUREMENT,
        "max-height" to PropertyType.MEASUREMENT,
        "max-width" to PropertyType.MEASUREMENT,
        "messagebox-text-interaction-flags" to PropertyType.NUMBER,
        "messagebox-critical-icon" to PropertyType.BORDER,
        "messagebox-information-icon" to PropertyType.BORDER,
        "messagebox-question-icon" to PropertyType.BORDER,
        "messagebox-warning-icon" to PropertyType.BORDER,
        "min-height" to PropertyType.MEASUREMENT,
        "min-width" to PropertyType.MEASUREMENT,
        "network-icon" to PropertyType.BORDER,
        "opacity" to PropertyType.NUMBER,
        "outline" to PropertyType.BORDER,
        "outline-bottom-left-radius" to PropertyType.MEASUREMENT,
        "outline-bottom-right-radius" to PropertyType.MEASUREMENT,
        "outline-color" to PropertyType.COLOR,
        "outline-offset" to PropertyType.MEASUREMENT,
        "outline-radius" to PropertyType.MEASUREMENT,
        "outline-style" to PropertyType.STRING,
        "outline-top-left-radius" to PropertyType.MEASUREMENT,
        "outline-top-right-radius" to PropertyType.MEASUREMENT,
        "outline-width" to PropertyType.MEASUREMENT,
        "padding" to PropertyType.MEASUREMENT,
        "padding-bottom" to PropertyType.MEASUREMENT,
        "padding-left" to PropertyType.MEASUREMENT,
        "padding-right" to PropertyType.MEASUREMENT,
        "padding-top" to PropertyType.MEASUREMENT,
        "paint-alternating-row-colors-for-empty-area" to PropertyType.NUMBER,
        "placeholder-text-color" to PropertyType.COLOR,
        "position" to PropertyType.STRING,
        "qproperty-alignment" to PropertyType.STRING,
        "qproperty-wordWrap" to PropertyType.NUMBER,
        "right" to PropertyType.MEASUREMENT,
        "rightarrow-icon" to PropertyType.BORDER,
        "selection-background-color" to PropertyType.COLOR,
        "selection-color" to PropertyType.COLOR,
        "show-decoration-selected" to PropertyType.NUMBER,
        "spacing" to PropertyType.MEASUREMENT,
        "subcontrol-origin" to PropertyType.STRING,
        "subcontrol-position" to PropertyType.STRING,
        "text-align" to PropertyType.STRING,
        "text-decoration" to PropertyType.STRING,
        "titlebar-contexthelp-icon" to PropertyType.BORDER,
        "titlebar-maximize-icon" to PropertyType.BORDER,
        "titlebar-menu-icon" to PropertyType.BORDER,
        "titlebar-minimize-icon" to PropertyType.BORDER,
        "titlebar-normal-icon" to PropertyType.BORDER,
        "titlebar-shade-icon" to PropertyType.BORDER,
        "titlebar-show-maximize-button" to PropertyType.NUMBER,
        "titlebar-show-minimize-button" to PropertyType.NUMBER,
        "titlebar-show-tooltips-on-buttons" to PropertyType.NUMBER,
        "titlebar-unshade-icon" to PropertyType.BORDER,
        "top" to PropertyType.MEASUREMENT,
        "trash-icon" to PropertyType.BORDER,
        "uparrow-icon" to PropertyType.BORDER,
        "width" to PropertyType.MEASUREMENT,
        "widget-animation-duration" to PropertyType.NUMBER,
        "word-spacing" to PropertyType.MEASUREMENT,
        "-qt-background-role" to PropertyType.STRING,
        "-qt-style-features" to PropertyType.STRING
    )

    // Helper for CompletionContributor
    val PROPERTIES = PROPERTY_TYPES.keys.toList()

    // List of standard Qt Widgets (Qt 6 + 5 superset)
    val WIDGET_SELECTORS = listOf(
        "QAbstractItemView",
        "QAbstractScrollArea",
        "QCalendarWidget",
        "QCheckBox",
        "QColumnView",
        "QComboBox",
        "QDateEdit",
        "QDateTimeEdit",
        "QDialog",
        "QDialogButtonBox",
        "QDockWidget",
        "QDoubleSpinBox",
        "QFrame",
        "QGroupBox",
        "QHeaderView",
        "QKeySequenceEdit",
        "QLabel",
        "QLineEdit",
        "QListView",
        "QListWidget",
        "QMainWindow",
        "QMdiArea",
        "QMdiSubWindow",
        "QMenu",
        "QMenuBar",
        "QMessageBox",
        "QPlainTextEdit",
        "QProgressBar",
        "QPushButton",
        "QRadioButton",
        "QScrollArea",
        "QScrollBar",
        "QSizeGrip",
        "QSlider",
        "QSpinBox",
        "QSplitter",
        "QStackedWidget",
        "QStatusBar",
        "QTabBar",
        "QTabWidget",
        "QTableView",
        "QTableWidget",
        "QTextBrowser",
        "QTextEdit",
        "QTimeEdit",
        "QToolBar",
        "QToolBox",
        "QToolButton",
        "QToolTip",
        "QTreeView",
        "QTreeWidget",
        "QWidget",
        "QWizard",
        "QWizardPage"
    )

    // List of pseudo-states
    val PSEUDO_STATES = listOf(
        ":active", ":adjoins-item", ":alternate", ":bottom", ":checked", ":closable", ":closed",
        ":default", ":dir", ":dir(ltr)", ":dir(rtl)", ":disabled", ":edit-focus", ":editable",
        ":enabled", ":exclusive", ":first", ":flat", ":floatable", ":focus", ":has-children", ":has-siblings",
        ":horizontal", ":hover", ":indeterminate", ":last", ":left", ":maximized", ":middle",
        ":minimized", ":movable", ":next-selected", ":no-frame", ":non-exclusive", ":non-exclusive-indicator",
        ":off", ":on", ":only-one", ":open", ":pressed", ":previous-selected", ":read-only",
        ":right", ":selected", ":top", ":unchecked", ":vertical", ":window"
    )

    // Map specific sub-controls to widgets
    val WIDGET_SUBCONTROLS = mapOf(
        "QAbstractItemView" to listOf("::item"),
        "QCheckBox" to listOf("::indicator"),
        "QColumnView" to listOf("::left-arrow", "::right-arrow"),
        "QComboBox" to listOf("::drop-down", "::down-arrow"),
        "QDateTimeEdit" to listOf("::up-button", "::down-button", "::up-arrow", "::down-arrow"),
        "QDockWidget" to listOf("::title", "::close-button", "::float-button"),
        "QDoubleSpinBox" to listOf("::up-button", "::down-button", "::up-arrow", "::down-arrow"),
        "QGroupBox" to listOf("::title", "::indicator", "::text"),
        "QHeaderView" to listOf("::section", "::down-arrow", "::up-arrow"),
        "QListView" to listOf("::item"),
        "QListWidget" to listOf("::item"),
        "QMainWindow" to listOf("::separator"),
        "QMdiSubWindow" to listOf("::title", "::close-button", "::minimize-button", "::maximize-button"),
        "QMenu" to listOf("::item", "::indicator", "::separator", "::tear-off", "::tearoff", "::icon", "::right-arrow", "::scroller"),
        "QMenuBar" to listOf("::item"),
        "QProgressBar" to listOf("::chunk"),
        "QPushButton" to listOf("::menu-indicator"),
        "QRadioButton" to listOf("::indicator"),
        "QScrollBar" to listOf("::handle", "::add-line", "::sub-line", "::add-page", "::sub-page", "::up-arrow", "::down-arrow", "::left-arrow", "::right-arrow"),
        "QSlider" to listOf("::groove", "::handle", "::add-page", "::sub-page"),
        "QSpinBox" to listOf("::up-button", "::down-button", "::up-arrow", "::down-arrow"),
        "QSplitter" to listOf("::handle"),
        "QStatusBar" to listOf("::item"),
        "QTabBar" to listOf("::tab", "::scroller", "::tear", "::close-button"),
        "QTabWidget" to listOf("::pane", "::tab-bar", "::left-corner", "::right-corner"),
        "QTableView" to listOf("::item"),
        "QTableWidget" to listOf("::item"),
        "QToolBar" to listOf("::separator", "::handle"),
        "QToolBox" to listOf("::tab"),
        "QToolButton" to listOf("::menu-button", "::menu-indicator", "::menu-arrow", "::down-arrow", "::left-arrow", "::right-arrow", "::up-arrow"),
        "QTreeView" to listOf("::item", "::branch"),
        "QTreeWidget" to listOf("::item", "::branch"),
        "QLabel" to emptyList(),
        "QLineEdit" to emptyList(),
        "QTextEdit" to emptyList(),
        "QPlainTextEdit" to emptyList(),
        "QFrame" to emptyList(),
        "QWidget" to emptyList(),
        "QDialog" to emptyList(),
    )

    // Common Subcontrols fallback
    val COMMON_SUBCONTROLS = listOf(
        "::add-line", "::add-page", "::branch", "::chunk", "::close-button", "::corner", "::down-arrow",
        "::down-button", "::drop-down", "::float-button", "::groove", "::handle", "::icon", "::indicator",
        "::item", "::left-arrow", "::left-corner", "::menu-arrow", "::menu-button", "::menu-indicator",
        "::pane", "::right-arrow", "::right-corner", "::scroller", "::section", "::separator", "::sub-line",
        "::sub-page", "::tab", "::tab-bar", "::tear", "::tear-off", "::tearoff", "::text", "::title",
        "::up-arrow", "::up-button"
    )

    // Values for Completion
    val COMMON_VALUES = listOf(
        "aliceblue", "antiquewhite", "aqua", "aquamarine", "azure", "beige", "bisque", "black", "blanchedalmond",
        "blue", "blueviolet", "bold", "bottom", "brown", "burlywood", "cadetblue", "center", "chartreuse",
        "chocolate", "coral", "cornflowerblue", "cornsilk", "crimson", "cyan", "darkblue", "darkcyan",
        "darkgoldenrod", "darkgray", "darkgreen", "darkgrey", "darkkhaki", "darkmagenta", "darkolivegreen",
        "darkorange", "darkorchid", "darkred", "darksalmon", "darkseagreen", "darkslateblue", "darkslategray",
        "darkslategrey", "darkturquoise", "darkviolet", "deeppink", "deepskyblue", "dimgray", "dimgrey",
        "dodgerblue", "firebrick", "floralwhite", "forestgreen", "fuchsia", "gainsboro", "ghostwhite", "gold",
        "goldenrod", "gray", "green", "greenyellow", "grey", "honeydew", "hotpink", "indianred", "indigo",
        "italic", "ivory", "khaki", "lavender", "lavenderblush", "lawngreen", "left", "lemonchiffon",
        "lightblue", "lightcoral", "lightcyan", "lightgoldenrodyellow", "lightgray", "lightgreen", "lightgrey",
        "lightpink", "lightsalmon", "lightseagreen", "lightskyblue", "lightslategray", "lightslategrey",
        "lightsteelblue", "lightyellow", "lime", "limegreen", "linen", "magenta", "maroon", "mediumaquamarine",
        "mediumblue", "mediumorchid", "mediumpurple", "mediumseagreen", "mediumslateblue", "mediumspringgreen",
        "mediumturquoise", "mediumvioletred", "midnightblue", "mintcream", "mistyrose", "moccasin", "navajowhite",
        "navy", "none", "normal", "oldlace", "olive", "olivedrab", "orange", "orangered", "orchid",
        "palegoldenrod", "palegreen", "paleturquoise", "palevioletred", "papayawhip", "peachpuff", "peru",
        "pink", "plum", "powderblue", "purple", "red", "repeat", "repeat-x", "repeat-y", "right",
        "rosybrown", "royalblue", "saddlebrown", "salmon", "sandybrown", "seagreen", "seashell", "sienna",
        "silver", "skyblue", "slateblue", "slategray", "slategrey", "snow", "solid", "springgreen",
        "steelblue", "tan", "teal", "thistle", "tomato", "top", "transparent", "turquoise", "underline",
        "violet", "wheat", "white", "whitesmoke", "yellow", "yellowgreen"
    )

    // Functions
    val FUNCTIONS = listOf(
        "url()", "rgb()", "rgba()", "hsv()", "hsva()", "hsl()", "hsla()", "qlineargradient()",
        "qradialgradient()", "qconicalgradient()", "palette()"
    )

    // Units
    val UNITS = listOf("px", "pt", "em", "ex")
}
